language: ruby
cache: bundler
rvm:
  - 2.1.2
services:
  - mongodb
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm install -g bower
  - bower install
script:
  - RAILS_ENV=test bundle exec rspec spec
  - npm run test-ci
