# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68d310e0bf341fc571bbb54399c2ec608021e5c59650eab57bc9f0677eb0ba7ddcf69dd38c42df0084da2672663991fd0e2ab2101ea245e089dfb513feb899e0

test:
  secret_key_base: f003e69e17915b0b725237d301b141cea56c332aeae487948d77dd63d0c65cd83f2ed97a924d3aa6905ede85c5448e6bfdc17919bee4768da741547dc71b8dd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
