# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af629fc005a461b331322bbbcd973878e3feb681548569fe1177ddbe1773ae1c88e3ee4b06d060bb6d0436e446da9e1a68c25c8dd5cee2bb74c919bd034f9f2a

test:
  secret_key_base: 162a5f15bab04b5a6e195bcd1ed76faf1df741338eb47ae5282b774d6272f44b048a3944a181e34601152c4593758e5452fbcad530c9d0665c7680ea5b30400d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
